materials:
  Carbon Epoxy:
    density: 1605  # Density in kg/m^3
    cost_factor: 36  # Cost factor (arbitrary units)
    Xt: 2.06  # Tensile strength in the longitudinal direction (MPa)
    Xc: 1.7  # Compressive strength in the longitudinal direction (MPa)
    Yt: 0.07  # Tensile strength in the transverse direction (MPa)
    Yc: 0.24  # Compressive strength in the transverse direction (MPa)
    S: 0.11  # Shear strength (MPa)
  Glass Epoxy:
    density: 1993  # Density in kg/m^3
    cost_factor: 10  # Cost factor (arbitrary units)
    Xt: 1.13  # Tensile strength in the longitudinal direction (MPa)
    Xc: 1.03  # Compressive strength in the longitudinal direction (MPa)
    Yt: 0.05  # Tensile strength in the transverse direction (MPa)
    Yc: 0.15  # Compressive strength in the transverse direction (MPa)
    S: 0.08  # Shear strength (MPa)
  Kevlar Epoxy:
    density: 1380  # Density in kg/m^3
    cost_factor: 44  # Cost factor (arbitrary units)
    Xt: 1.28  # Tensile strength in the longitudinal direction (MPa)
    Xc: 0.34  # Compressive strength in the longitudinal direction (MPa)
    Yt: 0.03  # Tensile strength in the transverse direction (MPa)
    Yc: 0.16  # Compressive strength in the transverse direction (MPa)
    S: 0.05  # Shear strength (MPa)

gravity: 9.81  # Acceleration due to gravity (m/s^2)
min_ply: 4  # Minimum number of plies in a laminate
max_ply: 7  # Maximum number of plies in a laminate

ga_params:
  crossover_prob: 0.67  # Probability of performing crossover between parents
  mutation_prob: 0.10  # Probability of mutating a ply within a laminate
  plyswap_prob: 0.50  # Probability of swapping two plies within a laminate
  plyadd_prob: 0.10  # Probability of adding a new ply to the laminate
  plydel_prob: 0.10  # Probability of deleting the outermost ply from the laminate
  elite_fraction: 0.70  # Fraction of the top individuals retained in the next generation
  selection_method: tournament  # Selection method ('tournament', 'roulette', 'rank')
  crossover_method: multi-point  # Crossover method ('single-point', 'multi-point', 'uniform')
  adaptive_mutation: true  # Whether mutation rates adapt based on population diversity
  diversity_threshold: 0.2  # Threshold for population diversity below which mutation rate increases
  mutation_rate_adaptive_factor: 0.05  # Factor to increase mutation rate if diversity is low
